### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by RPE8** [RPE8/shiny-palm-tree#4]

**Comment by mikitaaB** [comment]
В файле `package-lock.json` в `dependencies` присутсвует `sass`, который установится после выполнения команды `npm install`. Если при запуске файлов возникают ошибки, то `sass` следует  [установить и настроить согласно документации](https://create-react-app.dev/docs/adding-a-sass-stylesheet/). Для запуска `sass `и компиляции `.sass` и `.scss` файлов в `.css` файлы выполняется команда `sass src/style/index.scss src/style/index.css`

**Comment by RPE8** [comment]
> В файле `package-lock.json` в `dependencies` присутсвует `sass`, который установится после выполнения команды `npm install`. Если при компиляции `.scss` файлов возникают ошибки, то `sass` следует [установить и настроить согласно документации](https://create-react-app.dev/docs/adding-a-sass-stylesheet/). Для запуска `sass `и компиляции `.sass` и `.scss` файлов в `.css` файлы выполняется команда `sass src/style/index.scss src/style/index.css`

1) Как использовать это в процессе разработки? Ведь сейчас ты просто продублировал стили в `.css` на своей ветке, так?  
2) Т.е. если у нас появятся новые `.scss` файлы, то нужно будет их добавлять в `sass src/style/index.scss src/style/index.css`

**Comment by mikitaaB** [comment]
> > В файле `package-lock.json` в `dependencies` присутсвует `sass`, который установится после выполнения команды `npm install`. Если при компиляции `.scss` файлов возникают ошибки, то `sass` следует [установить и настроить согласно документации](https://create-react-app.dev/docs/adding-a-sass-stylesheet/). Для запуска `sass `и компиляции `.sass` и `.scss` файлов в `.css` файлы выполняется команда `sass src/style/index.scss src/style/index.css`
> 
> 1. Как использовать это в процессе разработки? Ведь сейчас ты просто продублировал стили в `.css` на своей ветке, так?
> 2. Т.е. если у нас появятся новые `.scss` файлы, то нужно будет их добавлять в `sass src/style/index.scss src/style/index.css`

1. Стили были переведены из `scss` в `css`. Сначала стили пишутся в scss файле с применением возможностей `scss` и затем переводится в `css`, который потом применяется в приложении
2. Когда появятся новые файлы, то [компилировать по несколько файлов или директориями (многие ко многим)](https://sass-lang.com/documentation/cli/dart-sass)
Несколько файлов: `sass src/style/index.scss:src/style/index.css src/style/newStyle.scss:src/style/newStyle.css` 
Директории: `sass src/style:src/style`

**Comment by RPE8** [comment]
@mikitaaB вот было бы круто, если этот процесс был автоматизирован в `react-scripts build`
Мб, там можно конфиги создать для этого...

**Comment by mikitaaB** [comment]
> @mikitaaB вот было бы круто, если этот процесс был автоматизирован в `react-scripts build` Мб, там можно конфиги создать для этого...

Добавлено. Запускается командой `npm run scss`. Предварительно нужно установить пакет `node-sass`

**Comment by RPE8** [comment]
https://create-react-app.dev/docs/adding-a-sass-stylesheet
